<?php

namespace Database\Seeders;

use App\Models\CaseStatus;
use Illuminate\Database\Seeder;

class CaseStatusesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        CaseStatus::insert([
            [
                'code' => 'DRAFT',
                'name' => 'Draft',
                'description' => 'Case is in draft status',
                'stage_number' => 1,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SUBMITTED',
                'name' => 'Submitted',
                'description' => 'Case has been submitted',
                'stage_number' => 1,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SP2_RECEIVED',
                'name' => 'SP2 Received',
                'description' => 'Audit notification (SP2) has been received',
                'stage_number' => 2,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SPHP_RECEIVED',
                'name' => 'SPHP Received',
                'description' => 'Audit findings notification (SPHP) has been received',
                'stage_number' => 3,
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SKP_RECEIVED',
                'name' => 'SKP Received',
                'description' => 'Tax assessment letter (SKP) has been received',
                'stage_number' => 4,
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'OBJECTION_SUBMITTED',
                'name' => 'Objection Submitted',
                'description' => 'Objection (Surat Keberatan) has been submitted',
                'stage_number' => 5,
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SPUH_RECEIVED',
                'name' => 'SPUH Received',
                'description' => 'Objection response (SPUH) has been received',
                'stage_number' => 6,
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'OBJECTION_DECISION_RECEIVED',
                'name' => 'Objection Decision Received',
                'description' => 'Objection decision (Keputusan Keberatan) has been received',
                'stage_number' => 7,
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'APPEAL_SUBMITTED',
                'name' => 'Appeal Submitted',
                'description' => 'Appeal (Surat Banding) has been submitted',
                'stage_number' => 8,
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'APPEAL_EXPLANATION_REQUESTED',
                'name' => 'Appeal Explanation Requested',
                'description' => 'Appeal explanation (Permintaan Penjelasan Banding) has been requested',
                'stage_number' => 9,
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'APPEAL_DECISION_RECEIVED',
                'name' => 'Appeal Decision Received',
                'description' => 'Appeal decision (Keputusan Banding) has been received',
                'stage_number' => 10,
                'sort_order' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SUPREME_COURT_SUBMITTED',
                'name' => 'Supreme Court Review Submitted',
                'description' => 'Supreme court review (Peninjauan Kembali) has been submitted',
                'stage_number' => 11,
                'sort_order' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SUPREME_COURT_DECISION_RECEIVED',
                'name' => 'Supreme Court Decision Received',
                'description' => 'Supreme court decision (Keputusan Peninjauan Kembali) has been received',
                'stage_number' => 11,
                'sort_order' => 13,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'REFUND_IN_PROGRESS',
                'name' => 'Refund In Progress',
                'description' => 'Refund is being processed',
                'stage_number' => 12,
                'sort_order' => 14,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'REFUND_COMPLETED',
                'name' => 'Refund Completed',
                'description' => 'Refund has been completed',
                'stage_number' => 12,
                'sort_order' => 15,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'KIAN_SUBMITTED',
                'name' => 'KIAN Submitted',
                'description' => 'Correction request (KIAN) has been submitted',
                'stage_number' => 12,
                'sort_order' => 16,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'CLOSED',
                'name' => 'Closed',
                'description' => 'Case has been closed',
                'stage_number' => 13,
                'sort_order' => 17,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
