<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EntitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('entities')->insert([
            [
                'code' => 'PASI',
                'name' => 'PT. Autocomp System Indonesia',
                'entity_type' => 'HOLDING',
                'parent_entity_id' => null,
                'tax_id' => '07.123.456.7-901.000', // Dummy NPWP format
                'registration_number' => '01.02.0000123456',
                'business_address' => 'Jl. Industri Raya No. 1, Jakarta Utara',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '14240',
                'country' => 'Indonesia',
                'phone' => '+62-21-1234567',
                'fax' => '+62-21-1234568',
                'email' => 'info@pasi.co.id',
                'industry_code' => '29.10.11',
                'industry_name' => 'Manufacture of Motor Vehicles',
                'annual_revenue' => 500000000000, // 500 billion IDR
                'employee_count' => 1500,
                'business_status' => 'ACTIVE',
                'established_date' => '1995-01-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PEMI',
                'name' => 'PT. EDS Manufacturing Indonesia',
                'entity_type' => 'AFFILIATE',
                'parent_entity_id' => 1,
                'tax_id' => '07.234.567.8-901.000',
                'registration_number' => '01.02.0000123457',
                'business_address' => 'Jl. Industri Raya No. 2, Jakarta Utara',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '14240',
                'country' => 'Indonesia',
                'phone' => '+62-21-7654321',
                'fax' => '+62-21-7654322',
                'email' => 'info@pemi.co.id',
                'industry_code' => '29.10.20',
                'industry_name' => 'Manufacture of Parts for Motor Vehicles',
                'annual_revenue' => 250000000000,
                'employee_count' => 800,
                'business_status' => 'ACTIVE',
                'established_date' => '2000-06-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SUAI',
                'name' => 'PT. Subang Autocomp Indonesia',
                'entity_type' => 'AFFILIATE',
                'parent_entity_id' => 1,
                'tax_id' => '07.345.678.9-012.000',
                'registration_number' => '01.02.0000123458',
                'business_address' => 'Jl. Industri No. 10, Subang',
                'city' => 'Subang',
                'province' => 'Jawa Barat',
                'postal_code' => '41212',
                'country' => 'Indonesia',
                'phone' => '+62-260-4567890',
                'fax' => '+62-260-4567891',
                'email' => 'info@suai.co.id',
                'industry_code' => '29.10.11',
                'industry_name' => 'Manufacture of Motor Vehicles',
                'annual_revenue' => 180000000000,
                'employee_count' => 600,
                'business_status' => 'ACTIVE',
                'established_date' => '2002-03-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SAMI',
                'name' => 'PT. Semarang Autocomp Indonesia',
                'entity_type' => 'AFFILIATE',
                'parent_entity_id' => 1,
                'tax_id' => '07.456.789.0-123.000',
                'registration_number' => '01.02.0000123459',
                'business_address' => 'Jl. Industri Mulia No. 5, Semarang',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50191',
                'country' => 'Indonesia',
                'phone' => '+62-24-7654321',
                'fax' => '+62-24-7654322',
                'email' => 'info@sami.co.id',
                'industry_code' => '29.30.19',
                'industry_name' => 'Manufacture of Other Parts and Accessories',
                'annual_revenue' => 150000000000,
                'employee_count' => 450,
                'business_status' => 'ACTIVE',
                'established_date' => '2003-07-22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SAI',
                'name' => 'PT. Surabaya Autocomp Indonesia',
                'entity_type' => 'AFFILIATE',
                'parent_entity_id' => 1,
                'tax_id' => '07.567.890.1-234.000',
                'registration_number' => '01.02.0000123460',
                'business_address' => 'Jl. Raya Industri No. 15, Surabaya',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60188',
                'country' => 'Indonesia',
                'phone' => '+62-31-7654321',
                'fax' => '+62-31-7654322',
                'email' => 'info@sai.co.id',
                'industry_code' => '29.10.20',
                'industry_name' => 'Manufacture of Parts for Motor Vehicles',
                'annual_revenue' => 120000000000,
                'employee_count' => 350,
                'business_status' => 'ACTIVE',
                'established_date' => '2005-09-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'JAI',
                'name' => 'PT. Jatim Autocomp Indonesia',
                'entity_type' => 'AFFILIATE',
                'parent_entity_id' => 1,
                'tax_id' => '07.678.901.2-345.000',
                'registration_number' => '01.02.0000123461',
                'business_address' => 'Jl. Industri Maju No. 20, Jatim',
                'city' => 'Malang',
                'province' => 'Jawa Timur',
                'postal_code' => '65000',
                'country' => 'Indonesia',
                'phone' => '+62-341-7654321',
                'fax' => '+62-341-7654322',
                'email' => 'info@jai.co.id',
                'industry_code' => '29.10.11',
                'industry_name' => 'Manufacture of Motor Vehicles',
                'annual_revenue' => 100000000000,
                'employee_count' => 300,
                'business_status' => 'ACTIVE',
                'established_date' => '2006-11-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
